### ISSUE TITLE
Update README.md with MVP Requirements 

### ISSUE THREAD

**Issue by jonnywatersbb** [bigbite/themer#63]
_For discussion before committing to `docs/README.md`_

## MVP Requirements
Minimum feature list required in order for this project to be considered stable.

- Should be tested on WordPress 5.8 and above and PHP 8+
- Load the active theme.json file from the current theme and render a UI to represent this to the user.
- Display live code preview of the theme.json file to instantly see how a setting change in the UI is altered in theme.json
- Dynamic support for all fields in theme.json
- Ability to edit the value of any theme.json field via the UI and save the changes
- Changes should be stored to the database in a manner compatible with WP Core, including the core styles UI
- Export/download an updated theme.json file
- Reset your overall changes and revert back to the original theme.json file
- Validation on all input fields
- Validation to prevent invalid changes to theme.json file
- Inform the user when a corrupt/invalid theme.json is loaded
- Fully compatible with multisite
- Match WP Core look and feel

**Comment by g-elwell** [comment]
Resolved by #110
